# Generated by Django 5.0.6 on 2024-06-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_des', models.TextField()),
                ('receipe_img', models.ImageField(upload_to='image')),
            ],
        ),
    ]
