# Generated by Django 5.0.6 on 2024-06-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_img',
            new_name='receipe_image',
        ),
    ]
