# Generated by Django 5.0.6 on 2024-07-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_generation')},
        ),
    ]
