# Generated by Django 5.0.6 on 2024-07-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_alter_reportcard_date_of_generation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='date_of_generation',
        ),
    ]
